site_name: Scalper
site_url: https://scalper.org/docs
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  favicon: images/dog-side.svg
  icon:
    logo: material/dog-side
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
nav:
  - index.md
  - Data System:
      - data-system/index.md
      - data-system/module-architecture.md
      - data-system/backends.md
      - data-system/schema-reference.md
  - Exchange Connector:
      - exchange-connector/index.md
      - exchange-connector/architecture.md
      - exchange-connector/api-reference.md
  - Strategy Manager:
      - strategy-manager/index.md
      - strategy-manager/creating-components.md
      - strategy-manager/reference.md
  - Backtesting Engine:
      - backtesting-engine/index.md
      - backtesting-engine/parameter-optimisation.md
      - backtesting-engine/profit-calculation.md
      - backtesting-engine/generalisation-evaluation.md
  - trade-executor.md
  - cloud-architecture.md
  - architecture-decision-log.md
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji
