[pytest]
pythonpath = scalper
testpaths = scalper/tests
markers =
    timestamp_conversion: Tests for timestamp conversion utilities.
    parse_datetime
    get_nano_timestamp
    get_second_timestamp