[pytest]
pythonpath = scalper
testpaths = scalper/tests
markers =
    get_objective
    calculate_penalty
    timestamp_conversion: Tests for timestamp conversion utilities.
    parse_datetime
    get_nano_timestamp
    get_second_timestamp
    trade_executor: Tests for the TradeExecutor class.
    execute_interval