[pytest]
pythonpath = scalper
testpaths = scalper/tests
markers =
    # Backtesting Engine
    get_objective
    calculate_penalty

    # Utils
    timestamp_conversion: Tests for timestamp conversion utilities.
    parse_datetime
    get_nano_timestamp
    get_second_timestamp

    # Trade Executor
    trade_executor: Tests for the TradeExecutor class.
    execute_interval

    # Data System - Module & Categories
    data_system: Tests for the data system module.
    clients: Tests for client classes.
    config: Tests for configuration classes.
    models: Tests for model/dataclass classes.
    repositories: Tests for repository classes.

    # Data System - Clients
    sqlalchemy_client: Tests for the SQLAlchemyClient class.
    supabase_client: Tests for the SupabaseClient class.

    # Data System - Config
    local_sqlite_config: Tests for the LocalSQLiteConfig class.
    supabase_config: Tests for the SupabaseConfig class.

    # Data System - Models
    bot_model: Tests for the Bot dataclass.
    bot_order_model: Tests for the BotOrder dataclass.
    bot_run_model: Tests for the BotRun dataclass.
    bot_tick_model: Tests for the BotTick dataclass.
    generalisation_evaluation_model: Tests for the GeneralisationEvaluation dataclass.
    trade_model: Tests for the Trade dataclass.

    # Data System - Repositories
    supabase_bot_repository: Tests for the SupabaseBotRepository class.
    supabase_bot_order_repository: Tests for the SupabaseBotOrderRepository class.
    supabase_bot_run_repository: Tests for the SupabaseBotRunRepository class.
    supabase_bot_tick_repository: Tests for the SupabaseBotTickRepository class.
    sqlalchemy_generalisation_evaluation_repository: Tests for the SQLAlchemyGeneralisationEvaluationRepository class.
    sqlalchemy_trade_repository: Tests for the SQLAlchemyTradeRepository class.