from dataclasses import asdict
from datetime import datetime
from decimal import Decimal
from uuid import UUID

from supabase import Client

from data_system.models import BotTick
from data_system.models.bot_tick_model import Signal
from .bot_tick_repository import BotTickRepository


class SupabaseBotTickRepository(BotTickRepository):
    TABLE_NAME = 'bot_ticks'

    def __init__(self, client: Client) -> None:
        self.client = client

    def add(self, bot_tick: BotTick) -> BotTick:
        record = asdict(bot_tick)
        record.pop('id', None)  # Remove id as it should be auto-generated by the database
        record['run_id'] = str(bot_tick.run_id)  # Convert UUID to string
        record['timestamp'] = bot_tick.timestamp.isoformat()  # Convert datetime to ISO format

        response = (self.client.table(self.TABLE_NAME).insert(record).execute())
        return self._to_bot_tick(response.data[0])

    def get_by_bot_id(self, bot_id: str) -> list[BotTick]:
        response = (
            self.client
            .table(self.TABLE_NAME)
            .select("*")
            .eq("bot_id", bot_id)
            .order("timestamp", desc=True)
            .execute()
        )
        return [self._to_bot_tick(row) for row in response.data]

    def _to_bot_tick(self, data: dict) -> BotTick:
        data['run_id'] = UUID(data['run_id'])
        data['timestamp'] = datetime.fromisoformat(data['timestamp'])
        data['price'] = Decimal(data['price'])
        data['balance_base'] = Decimal(data['balance_base'])
        data['balance_quote'] = Decimal(data['balance_quote'])
        data['signal'] = Signal(data['signal'])
        return BotTick(**data)
