from dataclasses import asdict
from datetime import datetime
from decimal import Decimal
from uuid import UUID

from supabase import Client

from data_system.models import BotTick
from data_system.models.bot_tick_model import Signal
from .bot_tick_repository import BotTickRepository


class SupabaseBotTickRepository(BotTickRepository):
    TABLE_NAME = 'bot_ticks'

    def __init__(self, client: Client) -> None:
        self.client = client

    def add(self, bot_tick: BotTick) -> BotTick:
        response = self.client.table(self.TABLE_NAME).insert(self._to_record(bot_tick)).execute()
        if not response.data:
            raise RuntimeError(f'Insert into {self.TABLE_NAME} returned no data')
        return self._to_bot_tick(response.data[0])

    def get_by_bot_id(self, bot_id: str) -> list[BotTick]:
        response = (
            self.client
            .table(self.TABLE_NAME)
            .select('*')
            .eq('bot_id', bot_id)
            .order('timestamp', desc=True)
            .execute()
        )
        return [self._to_bot_tick(row) for row in response.data]

    def _to_record(self, bot_tick: BotTick) -> dict:
        record = asdict(bot_tick)

        # Remove id as it should be auto-generated by the database
        record.pop('id', None)

        # Convert UUID to string and datetime to ISO format string
        record['run_id'] = str(bot_tick.run_id)
        record['timestamp'] = bot_tick.timestamp.isoformat()

        # Convert Decimal to string to avoid floating point issues in JSON
        record['price'] = str(bot_tick.price)
        record['balance_base'] = str(bot_tick.balance_base)
        record['balance_quote'] = str(bot_tick.balance_quote)

        return record

    def _to_bot_tick(self, data: dict) -> BotTick:
        data['run_id'] = UUID(data['run_id'])
        data['timestamp'] = datetime.fromisoformat(data['timestamp'])
        data['price'] = Decimal(str(data['price']))
        data['balance_base'] = Decimal(str(data['balance_base']))
        data['balance_quote'] = Decimal(str(data['balance_quote']))
        data['signal'] = Signal(data['signal'])
        return BotTick(**data)
