import pytest
from datetime import datetime, timezone
from decimal import Decimal
from unittest.mock import Mock, MagicMock, patch
from uuid import UUID

from sqlalchemy.exc import SQLAlchemyError

from data_system.clients import SQLAlchemyClient, SupabaseClient
from data_system.models import Bot, Trade, BotTick, BotRun, BotOrder
from data_system.models.bot_tick_model import Signal
from data_system.models.bot_order_model import OrderStatus, Side
from data_system.repositories import (
    SQLAlchemyTradeRepository,
    SupabaseBotOrderRepository,
    SupabaseBotRepository,
    SupabaseBotRunRepository,
    SupabaseBotTickRepository
)


@pytest.mark.integration
@pytest.mark.data_system_integration
class TestDataSystemIntegration:
    '''
    Integration tests for Data System module.

    These tests verify that the repository -> client stack works correctly
    by mocking only at the system boundary (database connections), covering:
    - Layer integration (repository -> client -> database SDK)
    - Domain transformations (raw database responses -> domain objects)
    - Error propagation through layers
    - Transaction handling and session management
    '''

    # ==================== Fixtures ====================

    @pytest.fixture
    def sample_trade(self) -> Trade:
        return Trade(
            trade_id=123456789,
            pair='XXBTZGBP',
            price=50000.0,
            volume=0.001,
            timestamp=1704067200.123456,
            side='b',
            order_type='m'
        )

    @pytest.fixture
    def sample_bot(self) -> Bot:
        return Bot(
            id='btc_1m_001',
            pair='XXBTZGBP',
            strategy_name='PrecisionTrendStrategy',
            strategy_version='v1.0.0',
            interval=1,
            parameters={'rsi_period': 14, 'threshold': 30}
        )

    @pytest.fixture
    def sample_bot_run(self) -> BotRun:
        return BotRun(
            id=UUID('12345678-1234-5678-1234-567812345678'),
            bot_id='btc_1m_001',
            started_at=datetime.now(timezone.utc)
        )

    @pytest.fixture
    def sample_bot_tick(self, sample_bot_run: BotRun) -> BotTick:
        return BotTick(
            id=None,  # Auto-generated by database
            run_id=sample_bot_run.id,
            bot_id='btc_1m_001',
            timestamp=datetime.now(timezone.utc),
            price=Decimal('50000.00'),
            balance_base=Decimal('1.5'),
            balance_quote=Decimal('75000.00'),
            signal=Signal.BUY
        )

    @pytest.fixture
    def sample_bot_order(self, sample_bot_run: BotRun) -> BotOrder:
        return BotOrder(
            run_id=sample_bot_run.id,
            bot_id='btc_1m_001',
            exchange_order_id='OFLMR7-XXXXX-XXXXXX',
            side=Side.BUY,
        )

    # ==================== SQLAlchemy Stack Integration Tests ====================

    def test_sqlalchemy_trade_repository_add_full_stack(self, sample_trade: Trade):
        '''
        Test full SQLAlchemy stack: repository -> client -> session -> execute.
        Verifies that domain objects flow through all layers correctly.
        '''
        # Given
        mock_session = MagicMock()
        mock_engine = Mock()

        with patch('data_system.clients.sqlalchemy_client.create_engine', return_value=mock_engine):
            with patch('data_system.clients.sqlalchemy_client.sessionmaker') as mock_sessionmaker:
                # Setup session factory
                mock_session_class = Mock()
                mock_session_class.return_value = mock_session
                mock_sessionmaker.return_value = mock_session_class

                # Create client and repository (let our code run)
                client = SQLAlchemyClient()
                repository = SQLAlchemyTradeRepository(client)

                # When
                repository.add([sample_trade])

        # Then - Verify session lifecycle and data transformation
        mock_session.execute.assert_called_once()
        call_args = mock_session.execute.call_args

        # Verify SQL statement contains expected table and columns
        sql_stmt = str(call_args[0][0])
        assert 'INSERT OR IGNORE INTO trades' in sql_stmt
        assert 'trade_id' in sql_stmt
        assert 'pair' in sql_stmt

        # Verify domain object was converted to dict for database
        records = call_args[0][1]
        assert len(records) == 1
        assert records[0]['trade_id'] == sample_trade.trade_id
        assert records[0]['pair'] == sample_trade.pair
        assert records[0]['price'] == sample_trade.price

        # Verify transaction lifecycle
        mock_session.commit.assert_called_once()
        mock_session.close.assert_called_once()

    def test_sqlalchemy_trade_repository_get_full_stack(self, sample_trade: Trade):
        '''
        Test full SQLAlchemy stack for queries.
        Verifies transformation from database rows to domain objects.
        '''
        # Given
        mock_session = MagicMock()
        mock_engine = Mock()

        # Mock database response - simulate SQLAlchemy result rows
        mock_result = Mock()
        mock_row = (
            sample_trade.trade_id,
            sample_trade.pair,
            sample_trade.price,
            sample_trade.volume,
            sample_trade.timestamp,
            sample_trade.side,
            sample_trade.order_type
        )
        mock_result.fetchall.return_value = [mock_row]
        mock_session.execute.return_value = mock_result

        with patch('data_system.clients.sqlalchemy_client.create_engine', return_value=mock_engine):
            with patch('data_system.clients.sqlalchemy_client.sessionmaker') as mock_sessionmaker:
                mock_session_class = Mock()
                mock_session_class.return_value = mock_session
                mock_sessionmaker.return_value = mock_session_class

                client = SQLAlchemyClient()
                repository = SQLAlchemyTradeRepository(client)

                # When
                trades = repository.get(pair='XXBTZGBP', start=1704067200.0, end=1704067300.0)

        # Then - Verify domain transformation
        assert len(trades) == 1
        trade = trades[0]
        assert isinstance(trade, Trade)
        assert trade.trade_id == sample_trade.trade_id
        assert trade.pair == sample_trade.pair
        assert trade.price == sample_trade.price
        assert trade.volume == sample_trade.volume
        assert trade.timestamp == sample_trade.timestamp
        assert trade.side == sample_trade.side
        assert trade.order_type == sample_trade.order_type

    def test_sqlalchemy_error_propagation_and_rollback(self, sample_trade: Trade):
        '''
        Test that SQLAlchemy errors propagate correctly and trigger rollback.
        '''
        # Given
        mock_session = MagicMock()
        mock_engine = Mock()
        mock_session.execute.side_effect = SQLAlchemyError('Database connection failed')

        with patch('data_system.clients.sqlalchemy_client.create_engine', return_value=mock_engine):
            with patch('data_system.clients.sqlalchemy_client.sessionmaker') as mock_sessionmaker:
                mock_session_class = Mock()
                mock_session_class.return_value = mock_session
                mock_sessionmaker.return_value = mock_session_class

                client = SQLAlchemyClient()
                repository = SQLAlchemyTradeRepository(client)

                # When / Then - Verify error propagates through stack
                with pytest.raises(SQLAlchemyError) as exc_info:
                    repository.add([sample_trade])

                assert 'Database connection failed' in str(exc_info.value)

                # Verify rollback was called
                mock_session.rollback.assert_called_once()
                mock_session.commit.assert_not_called()
                mock_session.close.assert_called_once()

    # ==================== Supabase Stack Integration Tests ====================

    def test_supabase_bot_repository_add_full_stack(self, sample_bot: Bot):
        '''
        Test full Supabase stack: repository -> client -> Supabase SDK.
        Verifies domain transformations and parameter handling.
        '''
        # Given
        with patch('data_system.clients.supabase_client.create_client') as mock_create_client:
            mock_supabase = MagicMock()
            mock_create_client.return_value = mock_supabase

            # Setup mock response chain
            mock_response = Mock()
            mock_response.data = [{
                'id': sample_bot.id,
                'pair': sample_bot.pair,
                'strategy_name': sample_bot.strategy_name,
                'strategy_version': sample_bot.strategy_version,
                'interval': sample_bot.interval,
                'parameters': sample_bot.parameters,
                'created_at': sample_bot.created_at.isoformat()
            }]
            mock_supabase.table.return_value.insert.return_value.execute.return_value = mock_response

            # Create client and repository (let our code run)
            client = SupabaseClient()
            repository = SupabaseBotRepository(client)

            # When
            result = repository.add(sample_bot)

        # Then - Verify domain transformation and Supabase calls
        assert isinstance(result, Bot)
        assert result.id == sample_bot.id
        assert result.pair == sample_bot.pair
        assert result.strategy_name == sample_bot.strategy_name

        # Verify Supabase SDK was called correctly
        mock_supabase.table.assert_called_with('bots')

        # Verify datetime was converted to ISO format for Supabase
        insert_call = mock_supabase.table.return_value.insert.call_args
        inserted_data = insert_call[0][0]
        assert isinstance(inserted_data['created_at'], str)
        assert 'T' in inserted_data['created_at']  # ISO format contains 'T'

    def test_supabase_bot_repository_get_full_stack(self, sample_bot: Bot):
        '''
        Test full Supabase stack for queries.
        Verifies transformation from Supabase response to domain object.
        '''
        # Given
        with patch('data_system.clients.supabase_client.create_client') as mock_create_client:
            mock_supabase = MagicMock()
            mock_create_client.return_value = mock_supabase

            # Setup mock response with ISO datetime string (as Supabase returns)
            mock_response = Mock()
            mock_response.data = [{
                'id': sample_bot.id,
                'pair': sample_bot.pair,
                'strategy_name': sample_bot.strategy_name,
                'strategy_version': sample_bot.strategy_version,
                'interval': sample_bot.interval,
                'parameters': sample_bot.parameters,
                'created_at': '2025-01-01T12:00:00+00:00'
            }]
            mock_supabase.table.return_value.select.return_value.eq.return_value.execute.return_value = mock_response

            client = SupabaseClient()
            repository = SupabaseBotRepository(client)

            # When
            result = repository.get('btc_1m_001')

        # Then - Verify domain transformation
        assert isinstance(result, Bot)
        assert result.id == sample_bot.id
        assert result.pair == sample_bot.pair

        # Verify datetime was converted from ISO string to datetime object
        assert isinstance(result.created_at, datetime)

        # Verify Supabase query chain
        mock_supabase.table.assert_called_with('bots')
        mock_supabase.table.return_value.select.assert_called_with('*')
        mock_supabase.table.return_value.select.return_value.eq.assert_called_with(
            'id', 'btc_1m_001')

    def test_supabase_bot_tick_complex_transformations(self, sample_bot_tick: BotTick):
        '''
        Test complex domain transformations: UUID, datetime, Decimal, Enum.
        Verifies all type conversions work through the full stack.
        '''
        # Given
        with patch('data_system.clients.supabase_client.create_client') as mock_create_client:
            mock_supabase = MagicMock()
            mock_create_client.return_value = mock_supabase

            # Setup mock response with database types (strings for UUID, datetime, numbers for Decimal)
            mock_response = Mock()
            mock_response.data = [{
                'id': 1,
                'run_id': str(sample_bot_tick.run_id),  # UUID as string
                'bot_id': sample_bot_tick.bot_id,
                'timestamp': sample_bot_tick.timestamp.isoformat(),  # datetime as ISO string
                'price': str(sample_bot_tick.price),  # Decimal as string
                'balance_base': str(sample_bot_tick.balance_base),
                'balance_quote': str(sample_bot_tick.balance_quote),
                'signal': sample_bot_tick.signal.value  # Enum as string value
            }]
            mock_supabase.table.return_value.insert.return_value.execute.return_value = mock_response

            client = SupabaseClient()
            repository = SupabaseBotTickRepository(client)

            # When
            result = repository.add(sample_bot_tick)

        # Then - Verify all type conversions
        assert isinstance(result, BotTick)
        assert isinstance(result.run_id, UUID)
        assert result.run_id == sample_bot_tick.run_id
        assert isinstance(result.timestamp, datetime)
        assert isinstance(result.price, Decimal)
        assert result.price == sample_bot_tick.price
        assert isinstance(result.balance_base, Decimal)
        assert isinstance(result.balance_quote, Decimal)
        assert isinstance(result.signal, Signal)
        assert result.signal == Signal.BUY

        # Verify conversions in the insert call
        insert_call = mock_supabase.table.return_value.insert.call_args
        inserted_data = insert_call[0][0]
        assert isinstance(inserted_data['run_id'], str)  # UUID converted to string
        assert isinstance(inserted_data['timestamp'], str)  # datetime converted to ISO string
        assert 'id' not in inserted_data  # Auto-generated fields should be removed

    def test_supabase_bot_tick_query_with_transformations(self, sample_bot_tick: BotTick):
        '''
        Test querying with complex type transformations.
        '''
        # Given
        with patch('data_system.clients.supabase_client.create_client') as mock_create_client:
            mock_supabase = MagicMock()
            mock_create_client.return_value = mock_supabase

            # Mock response from database
            mock_response = Mock()
            mock_response.data = [
                {
                    'id': 1,
                    'run_id': str(sample_bot_tick.run_id),
                    'bot_id': sample_bot_tick.bot_id,
                    'timestamp': '2025-01-01T12:00:00+00:00',
                    'price': '50000.00',
                    'balance_base': '1.5',
                    'balance_quote': '75000.00',
                    'signal': 'buy'
                },
                {
                    'id': 2,
                    'run_id': str(sample_bot_tick.run_id),
                    'bot_id': sample_bot_tick.bot_id,
                    'timestamp': '2025-01-01T13:00:00+00:00',
                    'price': '51000.00',
                    'balance_base': '1.4',
                    'balance_quote': '71400.00',
                    'signal': 'hold'
                }
            ]
            mock_supabase.table.return_value.select.return_value.eq.return_value.order.return_value.execute.return_value = mock_response

            client = SupabaseClient()
            repository = SupabaseBotTickRepository(client)

            # When
            results = repository.get_by_bot_id('btc_1m_001')

        # Then - Verify all items transformed correctly
        assert len(results) == 2

        for tick in results:
            assert isinstance(tick, BotTick)
            assert isinstance(tick.run_id, UUID)
            assert isinstance(tick.timestamp, datetime)
            assert isinstance(tick.price, Decimal)
            assert isinstance(tick.balance_base, Decimal)
            assert isinstance(tick.balance_quote, Decimal)
            assert isinstance(tick.signal, Signal)

        # Verify first tick details
        assert results[0].price == Decimal('50000.00')
        assert results[0].signal == Signal.BUY

        # Verify second tick details
        assert results[1].price == Decimal('51000.00')
        assert results[1].signal == Signal.HOLD

    def test_supabase_bot_run_add_full_stack(self, sample_bot_run: BotRun):
        '''
        Test full Supabase stack for bot_runs: repository -> client -> Supabase SDK.
        Verifies UUID and datetime type conversions through all layers.
        '''
        # Given
        with patch('data_system.clients.supabase_client.create_client') as mock_create_client:
            mock_supabase = MagicMock()
            mock_create_client.return_value = mock_supabase

            mock_response = Mock()
            mock_response.data = [{
                'id': str(sample_bot_run.id),
                'bot_id': sample_bot_run.bot_id,
                'started_at': sample_bot_run.started_at.isoformat(),
                'completed_at': None,
            }]
            mock_supabase.table.return_value.insert.return_value.execute.return_value = mock_response

            client = SupabaseClient()
            repository = SupabaseBotRunRepository(client)

            # When
            result = repository.add(sample_bot_run)

        # Then - Verify domain transformation
        assert isinstance(result, BotRun)
        assert isinstance(result.id, UUID)
        assert result.id == sample_bot_run.id
        assert isinstance(result.started_at, datetime)
        assert result.started_at == sample_bot_run.started_at
        assert result.completed_at is None

        # Verify Supabase was called correctly
        mock_supabase.table.assert_called_with('bot_runs')

        # Verify UUID and datetime were serialised for Supabase
        inserted = mock_supabase.table.return_value.insert.call_args[0][0]
        assert inserted['id'] == str(sample_bot_run.id)
        assert isinstance(inserted['started_at'], str)

    def test_supabase_bot_run_get_full_stack(self, sample_bot_run: BotRun):
        '''
        Test full Supabase stack for bot_runs queries.
        Verifies deserialistion from Supabase response to domain object.
        '''
        # Given
        with patch('data_system.clients.supabase_client.create_client') as mock_create_client:
            mock_supabase = MagicMock()
            mock_create_client.return_value = mock_supabase

            mock_response = Mock()
            mock_response.data = [{
                'id': str(sample_bot_run.id),
                'bot_id': sample_bot_run.bot_id,
                'started_at': '2025-01-01T12:00:00+00:00',
                'completed_at': '2025-01-01T13:00:00+00:00',
            }]
            mock_supabase.table.return_value.select.return_value.eq.return_value.execute.return_value = mock_response

            client = SupabaseClient()
            repository = SupabaseBotRunRepository(client)

            # When
            result = repository.get(sample_bot_run.id)

        # Then - Verify types were deserialised correctly
        assert isinstance(result, BotRun)
        assert isinstance(result.id, UUID)
        assert result.id == sample_bot_run.id
        assert isinstance(result.started_at, datetime)
        assert isinstance(result.completed_at, datetime)

        # Verify the UUID was converted to string for the query
        mock_supabase.table.return_value.select.return_value.eq.assert_called_with(
            'id', str(sample_bot_run.id)
        )

    def test_supabase_bot_run_get_returns_none_when_not_found(self, sample_bot_run: BotRun):
        # Given
        with patch('data_system.clients.supabase_client.create_client') as mock_create_client:
            mock_supabase = MagicMock()
            mock_create_client.return_value = mock_supabase

            mock_response = Mock()
            mock_response.data = []
            mock_supabase.table.return_value.select.return_value.eq.return_value.execute.return_value = mock_response

            client = SupabaseClient()
            repository = SupabaseBotRunRepository(client)

            # When
            result = repository.get(sample_bot_run.id)

        # Then
        assert result is None

    def test_supabase_bot_order_add_placed_order_full_stack(self, sample_bot_order: BotOrder):
        '''
        Test full Supabase stack for bot_orders add: repository -> client -> Supabase SDK.
        Uses a freshly-placed order where fill fields are null.
        Verifies UUID, datetime, Decimal, and Enum conversions through all layers.
        '''
        # Given
        with patch('data_system.clients.supabase_client.create_client') as mock_create_client:
            mock_supabase = MagicMock()
            mock_create_client.return_value = mock_supabase

            mock_response = Mock()
            mock_response.data = [{
                'id': str(sample_bot_order.id),
                'bot_id': sample_bot_order.bot_id,
                'run_id': str(sample_bot_order.run_id),
                'tick_id': None,
                'exchange_order_id': sample_bot_order.exchange_order_id,
                'side': sample_bot_order.side.value,
                'status': sample_bot_order.status.value,
                'placed_at': sample_bot_order.placed_at.isoformat(),
                'filled_at': None,
                'price': None,
                'volume': None,
                'fee': None,
            }]
            mock_supabase.table.return_value.insert.return_value.execute.return_value = mock_response

            client = SupabaseClient()
            repository = SupabaseBotOrderRepository(client)

            # When
            result = repository.add(sample_bot_order)

        # Then - Verify domain transformation
        assert isinstance(result, BotOrder)
        assert isinstance(result.id, UUID)
        assert result.id == sample_bot_order.id
        assert isinstance(result.run_id, UUID)
        assert result.run_id == sample_bot_order.run_id
        assert isinstance(result.placed_at, datetime)
        assert isinstance(result.side, Side)
        assert result.side == Side.BUY
        assert isinstance(result.status, OrderStatus)
        assert result.status == OrderStatus.PLACED
        assert result.filled_at is None
        assert result.price is None
        assert result.volume is None
        assert result.fee is None

        # Verify Supabase was called correctly
        mock_supabase.table.assert_called_with('bot_orders')

        # Verify type serialisation in the insert call
        inserted = mock_supabase.table.return_value.insert.call_args[0][0]
        assert inserted['id'] == str(sample_bot_order.id)
        assert inserted['run_id'] == str(sample_bot_order.run_id)
        assert isinstance(inserted['placed_at'], str)
        assert inserted['filled_at'] is None
        assert inserted['price'] is None

    def test_supabase_bot_order_add_filled_order_full_stack(self, sample_bot_run: BotRun):
        '''
        Test full Supabase stack for a filled bot_order with all fields populated.
        Verifies Decimal serialisation and the full type round-trip.
        '''
        # Given
        filled_order = BotOrder(
            bot_id='btc_1m_001',
            run_id=sample_bot_run.id,
            tick_id=42,
            exchange_order_id='OFLMR7-XXXXX-XXXXXX',
            side=Side.BUY,
            status=OrderStatus.FILLED,
            price=Decimal('50000.123456789012'),
            volume=Decimal('0.001'),
            fee=Decimal('0.50'),
            filled_at=datetime(2025, 1, 1, 12, 0, 0, tzinfo=timezone.utc),
        )

        with patch('data_system.clients.supabase_client.create_client') as mock_create_client:
            mock_supabase = MagicMock()
            mock_create_client.return_value = mock_supabase

            mock_response = Mock()
            mock_response.data = [{
                'id': str(filled_order.id),
                'bot_id': filled_order.bot_id,
                'run_id': str(filled_order.run_id),
                'tick_id': filled_order.tick_id,
                'exchange_order_id': filled_order.exchange_order_id,
                'side': filled_order.side.value,
                'status': filled_order.status.value,
                'placed_at': filled_order.placed_at.isoformat(),
                'filled_at': filled_order.filled_at.isoformat(),
                'price': str(filled_order.price),
                'volume': str(filled_order.volume),
                'fee': str(filled_order.fee),
            }]
            mock_supabase.table.return_value.insert.return_value.execute.return_value = mock_response

            client = SupabaseClient()
            repository = SupabaseBotOrderRepository(client)

            # When
            result = repository.add(filled_order)

        # Then - Verify all fill fields are deserialised correctly
        assert result.status == OrderStatus.FILLED
        assert isinstance(result.filled_at, datetime)
        assert result.filled_at == filled_order.filled_at
        assert isinstance(result.price, Decimal)
        assert result.price == filled_order.price
        assert isinstance(result.volume, Decimal)
        assert result.volume == filled_order.volume
        assert isinstance(result.fee, Decimal)
        assert result.fee == filled_order.fee
        assert result.tick_id == 42

        # Verify Decimals were converted to strings for Supabase
        inserted = mock_supabase.table.return_value.insert.call_args[0][0]
        assert inserted['price'] == str(filled_order.price)
        assert inserted['volume'] == str(filled_order.volume)
        assert inserted['fee'] == str(filled_order.fee)
        assert isinstance(inserted['filled_at'], str)

    def test_supabase_bot_order_get_by_bot_id_full_stack(self, sample_bot_run: BotRun):
        '''
        Test full Supabase stack for bot_orders query.
        Verifies that mixed PLACED/FILLED orders in the response are all deserialised correctly.
        '''
        # Given
        run_id_str = str(sample_bot_run.id)

        with patch('data_system.clients.supabase_client.create_client') as mock_create_client:
            mock_supabase = MagicMock()
            mock_create_client.return_value = mock_supabase

            mock_response = Mock()
            mock_response.data = [
                {
                    'id': 'aaaaaaaa-0000-0000-0000-000000000001',
                    'bot_id': 'btc_1m_001',
                    'run_id': run_id_str,
                    'tick_id': 10,
                    'exchange_order_id': 'ORDER-AAA',
                    'side': 'buy',
                    'status': 'filled',
                    'placed_at': '2025-01-01T12:00:00+00:00',
                    'filled_at': '2025-01-01T12:00:01+00:00',
                    'price': '50000.00',
                    'volume': '0.001',
                    'fee': '0.50',
                },
                {
                    'id': 'aaaaaaaa-0000-0000-0000-000000000002',
                    'bot_id': 'btc_1m_001',
                    'run_id': run_id_str,
                    'tick_id': None,
                    'exchange_order_id': 'ORDER-BBB',
                    'side': 'sell',
                    'status': 'placed',
                    'placed_at': '2025-01-01T13:00:00+00:00',
                    'filled_at': None,
                    'price': None,
                    'volume': None,
                    'fee': None,
                },
            ]
            mock_supabase.table.return_value.select.return_value.eq.return_value.order.return_value.execute.return_value = mock_response

            client = SupabaseClient()
            repository = SupabaseBotOrderRepository(client)

            # When
            results = repository.get_by_bot_id('btc_1m_001')

        # Then
        assert len(results) == 2

        filled = results[0]
        assert filled.status == OrderStatus.FILLED
        assert filled.side == Side.BUY
        assert isinstance(filled.price, Decimal)
        assert filled.price == Decimal('50000.00')
        assert isinstance(filled.filled_at, datetime)
        assert filled.tick_id == 10

        placed = results[1]
        assert placed.status == OrderStatus.PLACED
        assert placed.side == Side.SELL
        assert placed.price is None
        assert placed.filled_at is None
        assert placed.tick_id is None

        # Verify query chain was called correctly
        mock_supabase.table.assert_called_with('bot_orders')
        mock_supabase.table.return_value.select.return_value.eq.assert_called_with(
            'bot_id', 'btc_1m_001'
        )
        mock_supabase.table.return_value.select.return_value.eq.return_value.order.assert_called_with(
            'placed_at', desc=True
        )

    def test_supabase_error_propagation(self):
        '''
        Test that Supabase errors propagate correctly through the stack.
        '''
        # Given
        with patch('data_system.clients.supabase_client.create_client') as mock_create_client:
            mock_supabase = MagicMock()
            mock_create_client.return_value = mock_supabase

            # Simulate Supabase error
            mock_supabase.table.return_value.select.return_value.eq.return_value.execute.side_effect = \
                Exception('Supabase connection failed')

            client = SupabaseClient()
            repository = SupabaseBotRepository(client)

            # When / Then - Verify error propagates
            with pytest.raises(Exception) as exc_info:
                repository.get('btc_1m_001')

            assert 'Supabase connection failed' in str(exc_info.value)

    def test_supabase_returns_none_when_not_found(self):
        '''
        Test that repository correctly handles empty Supabase responses.
        '''
        # Given
        with patch('data_system.clients.supabase_client.create_client') as mock_create_client:
            mock_supabase = MagicMock()
            mock_create_client.return_value = mock_supabase

            # Mock empty response
            mock_response = Mock()
            mock_response.data = []
            mock_supabase.table.return_value.select.return_value.eq.return_value.execute.return_value = mock_response

            client = SupabaseClient()
            repository = SupabaseBotRepository(client)

            # When
            result = repository.get('nonexistent_bot')

        # Then
        assert result is None

    # ==================== Cross-Backend Consistency Tests ====================

    def test_multiple_repositories_work_independently(self, sample_bot: Bot, sample_trade: Trade):
        '''
        Test that different repositories can be used together without conflicts.
        Verifies independent operation of SQLAlchemy and Supabase stacks.
        '''
        # Given - Setup both backends
        mock_sqlalchemy_session = MagicMock()
        mock_sqlalchemy_engine = Mock()

        with patch('data_system.clients.sqlalchemy_client.create_engine', return_value=mock_sqlalchemy_engine):
            with patch('data_system.clients.sqlalchemy_client.sessionmaker') as mock_sessionmaker:
                with patch('data_system.clients.supabase_client.create_client') as mock_create_client:
                    # Setup SQLAlchemy
                    mock_session_class = Mock()
                    mock_session_class.return_value = mock_sqlalchemy_session
                    mock_sessionmaker.return_value = mock_session_class

                    # Setup Supabase
                    mock_supabase = MagicMock()
                    mock_create_client.return_value = mock_supabase
                    mock_response = Mock()
                    mock_response.data = [{
                        'id': sample_bot.id,
                        'pair': sample_bot.pair,
                        'strategy_name': sample_bot.strategy_name,
                        'strategy_version': sample_bot.strategy_version,
                        'interval': sample_bot.interval,
                        'parameters': sample_bot.parameters,
                        'created_at': sample_bot.created_at.isoformat()
                    }]
                    mock_supabase.table.return_value.insert.return_value.execute.return_value = mock_response

                    # Create clients and repositories
                    sqlalchemy_client = SQLAlchemyClient()
                    supabase_client = SupabaseClient()
                    trade_repo = SQLAlchemyTradeRepository(sqlalchemy_client)
                    bot_repo = SupabaseBotRepository(supabase_client)

                    # When - Use both repositories
                    trade_repo.add([sample_trade])
                    bot = bot_repo.add(sample_bot)

        # Then - Both operations should succeed
        mock_sqlalchemy_session.execute.assert_called_once()
        mock_sqlalchemy_session.commit.assert_called_once()
        mock_supabase.table.assert_called()
        assert bot.id == sample_bot.id
